### ISSUE TITLE
Cannot load local ass file automatically?

### ISSUE THREAD

**Issue by Virtual-Circuit** [ScorpioPlayer/Feedback#28]
Most of the other player like KODI can choose local subtitle file automatically.
However, on XBOX each time I choose another video to play, I must select the correct ass file in a long list manually. 
 It makes me feel troublesome.

**Comment by bosxixi** [comment]
instead of open the video, please open the folder which contains both video and the ass subatitle file.
because UWP does not have permission to read any file from file system. 
open the folder means you have grant the app to access to the folder and it's child contents.

or use the Favourite feature.
